name: Update streak stats

on:
  schedule:
    - cron: "0 3 * * *" # Run every day at 03:00
  push:
    paths:
      - ".github/workflows/streak-stats.yml" # Run any time this file is modified
  workflow_dispatch: # Run manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate streak stats with default theme
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=${{ github.repository_owner }}&theme=default&card_width=854
          path: assets/streak/shijistar-default.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate streak stats with github-dark theme
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=${{ github.repository_owner }}&theme=github-dark&card_width=854
          path: assets/streak/shijistar-github-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate streak stats with github-light theme
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=${{ github.repository_owner }}&theme=github-light&card_width=854
          path: assets/streak/shijistar-github-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit streak stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/streak
          git commit -m "chore: update streak stats" || exit 0
          git push
